# --- Dev image: Maven + JDK ---
FROM maven:3.9.6-eclipse-temurin-21

WORKDIR /app

# # Install Python + venv for fillDB.py
# RUN apt-get update && \
#     apt-get install -y python3 python3-venv python3-pip curl && \
#     rm -rf /var/lib/apt/lists/*

# # Create virtual environment for Python dependencies
# RUN python3 -m venv /opt/venv
# ENV PATH="/opt/venv/bin:$PATH"
# RUN pip install --upgrade pip
# RUN pip install requests faker

# # Copy only scripts (code will come from bind mount)
# COPY scripts/fillDB.py /app//scripts/fillDB.py
# COPY /scripts/entrypoint.sh /app/scripts/entrypoint.sh
# RUN chmod +x /app/scripts/entrypoint.sh

# ENTRYPOINT ["/app/scripts/entrypoint.sh"]

# Start Spring Boot with hot reload (Maven)
CMD ["./mvnw", "spring-boot:run"]
