spring.application.name=backend
spring.config.import=optional:file:.env[.properties]

spring.profiles.active=${STAGE}

spring.mvc.servlet.path=${BASE_PATH}

spring.flyway.schemas=public
spring.flyway.default-schema=public
